import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import sitesRouter from "./sites";
import dashboardRouter from "./dashboard";
import linkGraphRouter from "./linkGraph";
import knowledgeGraphRouter from "./knowledgeGraph";
import inventoryRouter from "./inventory";
import suggestionsRouter from "./suggestions";
import losersRouter from "./losers";
import optimizeRouter from "./optimize";
import jobsRouter from "./jobs";
import gscRouter from "./gsc";
import gscChatRouter from "./gscChat";
import gscBulkQueriesRouter from "./gscBulkQueries";
import wpAdminRouter from "./wpAdmin";
import auditsRouter from "./audits";
import pruningRouter from "./pruning";
import linkingSettingsRouter from "./linkingSettings";
import linkLookupsRouter from "./linkLookups";
import dashboardUrlsRouter from "./dashboardUrls";
import contentRouter from "./content";
import alertsRouter from "./alerts";
import structuralRouter from "./structural";
import snapshotRouter from "./snapshot";
import keywordsRouter from "./keywords";
import kbRouter from "./kb";
import trackedSubmissionsRouter from "./trackedSubmissions";
import keywordReportRouter from "./keywordReport";
import ga4Router from "./ga4";
import reportRouter from "./report";
import actionsRouter from "./actions";
import impactRouter from "./impact";
import healthScoreRouter from "./healthScore";
import digestsRouter from "./digests";
import clusteringRouter from "./clustering";
import similarityRouter from "./similarity";
import bingRouter from "./bing";
import topicalMapRouter from "./topicalMap";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(sitesRouter);
router.use(dashboardRouter);
router.use(linkGraphRouter);
router.use(knowledgeGraphRouter);
router.use(inventoryRouter);
router.use(suggestionsRouter);
router.use(losersRouter);
router.use(optimizeRouter);
router.use(jobsRouter);
router.use(gscRouter);
router.use(gscChatRouter);
router.use(gscBulkQueriesRouter);
router.use(wpAdminRouter);
router.use(auditsRouter);
router.use(pruningRouter);
router.use(linkingSettingsRouter);
router.use(linkLookupsRouter);
router.use(dashboardUrlsRouter);
router.use(contentRouter);
router.use(alertsRouter);
router.use(structuralRouter);
router.use(snapshotRouter);
router.use(keywordsRouter);
router.use(kbRouter);
router.use(trackedSubmissionsRouter);
router.use(keywordReportRouter);
router.use(ga4Router);
router.use(reportRouter);
router.use(actionsRouter);
router.use(impactRouter);
router.use(healthScoreRouter);
router.use(digestsRouter);
router.use(clusteringRouter);
router.use(similarityRouter);
router.use(bingRouter);
router.use(topicalMapRouter);

export default router;
