/**
 * Client-side toxicity scoring for backlink referring domains.
 *
 * Signals used (all derived from data already fetched, no extra API cost):
 *   - Suspicious TLD (heavily abused in link spam)
 *   - Domain rank: low (<10) or unranked signals low-quality sites
 *   - High backlink volume from one domain (≥50) suggests sitewide/footer placement
 *   - Many links from a low-authority domain
 */

export type RiskLevel = "low" | "medium" | "high";

export interface DomainRisk {
  flags: string[];
  level: RiskLevel;
}

/** TLDs that are disproportionately represented in link-spam campaigns. */
const SUSPICIOUS_TLDS = new Set([
  "xyz",
  "click",
  "loan",
  "top",
  "club",
  "gq",
  "ml",
  "ga",
  "cf",
  "tk",
  "pw",
  "country",
  "stream",
  "download",
  "work",
  "cricket",
  "science",
  "racing",
  "date",
  "review",
  "trade",
  "win",
  "bid",
  "party",
  "accountant",
  "webcam",
  "faith",
  "men",
  "icu",
  "buzz",
  "rest",
  "online",
  "site",
]);

export function scoreDomain(
  domain: string,
  rank: number | null | undefined,
  backlinks: number,
): DomainRisk {
  const flags: string[] = [];

  // 1. Suspicious TLD
  const tld = domain.split(".").pop()?.toLowerCase() ?? "";
  if (SUSPICIOUS_TLDS.has(tld)) {
    flags.push("Suspicious TLD");
  }

  // 2. Rank signals (DataForSEO rank 0–1000; higher = more authoritative)
  if (rank === null || rank === undefined) {
    flags.push("Unranked domain");
  } else if (rank < 10) {
    flags.push("Very low authority (rank < 10)");
  } else if (rank < 30) {
    flags.push("Low authority (rank < 30)");
  }

  // 3. Sitewide-link signal: many backlinks from one domain → likely footer/sidebar
  if (backlinks >= 50) {
    flags.push("High link volume — possible sitewide placement");
  } else if (backlinks >= 20 && (rank == null || rank < 30)) {
    flags.push("Many links from low-authority domain");
  }

  // Determine overall level
  const highCount = flags.filter(
    (f) =>
      f.includes("Very low") ||
      f.includes("Suspicious TLD") ||
      f.includes("sitewide"),
  ).length;

  let level: RiskLevel = "low";
  if (highCount >= 2 || flags.length >= 3) level = "high";
  else if (highCount >= 1 || flags.length >= 2) level = "medium";

  return { flags, level };
}

export function isDomainFlagged(risk: DomainRisk): boolean {
  return risk.level === "medium" || risk.level === "high";
}

/** Generate a Google-format disavow file from a list of domains. */
export function buildDisavowTxt(domains: string[]): string {
  const header = [
    "# Disavow file generated by Linkweave",
    `# Generated: ${new Date().toISOString().slice(0, 10)}`,
    "# Upload at https://search.google.com/search-console/disavow-links",
    "",
  ].join("\n");
  return header + domains.map((d) => `domain:${d}`).join("\n") + "\n";
}
